export interface Question {
  id: number;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  category: 'planets' | 'history' | 'stars' | 'missions';
}

export const questions: Question[] = [
  {
    id: 1,
    question: 'Which is the largest planet in our solar system?',
    options: ['Saturn', 'Jupiter', 'Neptune', 'Uranus'],
    correct: 1,
    explanation: 'Jupiter is so massive that all other planets in the solar system could fit inside it with room to spare.',
    difficulty: 'easy',
    category: 'planets',
  },
  {
    id: 2,
    question: 'What is the closest star to Earth (besides the Sun)?',
    options: ['Sirius', 'Betelgeuse', 'Proxima Centauri', 'Vega'],
    correct: 2,
    explanation: 'Proxima Centauri is approximately 4.24 light-years from Earth, making it our nearest stellar neighbor.',
    difficulty: 'medium',
    category: 'stars',
  },
  {
    id: 3,
    question: 'In what year did humans first land on the Moon?',
    options: ['1965', '1967', '1969', '1972'],
    correct: 2,
    explanation: 'Apollo 11 landed on July 20, 1969. Neil Armstrong was the first human to step on the lunar surface.',
    difficulty: 'easy',
    category: 'history',
  },
  {
    id: 4,
    question: 'Which planet has the most confirmed moons?',
    options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    correct: 1,
    explanation: 'Saturn surpassed Jupiter in 2023 with 146 confirmed moons, making it the moon champion of the solar system.',
    difficulty: 'medium',
    category: 'planets',
  },
  {
    id: 5,
    question: 'What is the name of the first artificial satellite launched into space?',
    options: ['Explorer 1', 'Vostok 1', 'Sputnik 1', 'Luna 1'],
    correct: 2,
    explanation: 'Sputnik 1 was launched by the Soviet Union on October 4, 1957, beginning the Space Age.',
    difficulty: 'easy',
    category: 'history',
  },
  {
    id: 6,
    question: 'Which planet rotates on its side with an axial tilt of ~98°?',
    options: ['Neptune', 'Venus', 'Uranus', 'Mars'],
    correct: 2,
    explanation: 'Uranus has an axial tilt of 97.77°, essentially rolling along its orbit on its side.',
    difficulty: 'medium',
    category: 'planets',
  },
  {
    id: 7,
    question: 'What is a light-year?',
    options: [
      '365 days measured in space',
      'The distance light travels in one year',
      'The speed of light per second',
      'The age of a star in years',
    ],
    correct: 1,
    explanation: 'A light-year is a unit of distance — approximately 9.46 trillion kilometers — not a measure of time.',
    difficulty: 'easy',
    category: 'stars',
  },
  {
    id: 8,
    question: 'Which Mars rover is still active as of 2024?',
    options: ['Spirit', 'Opportunity', 'Curiosity', 'Sojourner'],
    correct: 2,
    explanation: 'Curiosity has been exploring Gale Crater since August 2012 and continues to send data back to Earth.',
    difficulty: 'medium',
    category: 'missions',
  },
  {
    id: 9,
    question: 'What is the hottest planet in our solar system?',
    options: ['Mercury', 'Venus', 'Mars', 'Jupiter'],
    correct: 1,
    explanation: 'Venus has a dense CO₂ atmosphere that creates a runaway greenhouse effect, averaging 465 °C at the surface.',
    difficulty: 'medium',
    category: 'planets',
  },
  {
    id: 10,
    question: 'Which telescope was launched on Christmas Day 2021?',
    options: ['Hubble', 'Spitzer', 'Chandra', 'James Webb'],
    correct: 3,
    explanation: 'The James Webb Space Telescope launched on December 25, 2021 and became humanity\'s most powerful space observatory.',
    difficulty: 'easy',
    category: 'missions',
  },
  {
    id: 11,
    question: 'How long does light from the Sun take to reach Earth?',
    options: ['1 second', 'About 8 minutes', '1 hour', '1 day'],
    correct: 1,
    explanation: 'Light from the Sun takes approximately 8 minutes and 20 seconds to travel the 150 million km to Earth.',
    difficulty: 'medium',
    category: 'stars',
  },
  {
    id: 12,
    question: 'What is the Great Red Spot on Jupiter?',
    options: ['A massive volcano', 'A large impact crater', 'A giant persistent storm', 'A liquid ocean'],
    correct: 2,
    explanation: 'The Great Red Spot is an anticyclonic storm larger than Earth that has persisted for at least 350 years.',
    difficulty: 'medium',
    category: 'planets',
  },
  {
    id: 13,
    question: 'Who was the first human to travel to space?',
    options: ['Neil Armstrong', 'Buzz Aldrin', 'Alan Shepard', 'Yuri Gagarin'],
    correct: 3,
    explanation: 'Yuri Gagarin completed one full orbit of Earth on April 12, 1961 aboard Vostok 1.',
    difficulty: 'easy',
    category: 'history',
  },
  {
    id: 14,
    question: 'What is the Milky Way?',
    options: ['A large planet', 'One of Saturn\'s moons', 'Our home galaxy', 'A type of nebula'],
    correct: 2,
    explanation: 'The Milky Way is a barred spiral galaxy estimated to contain 200–400 billion stars, including our Sun.',
    difficulty: 'easy',
    category: 'stars',
  },
  {
    id: 15,
    question: 'Which planet has a day longer than its year?',
    options: ['Mars', 'Mercury', 'Venus', 'Neptune'],
    correct: 2,
    explanation: 'Venus takes 243 Earth days to rotate once but only 225 Earth days to orbit the Sun — its day outlasts its year.',
    difficulty: 'hard',
    category: 'planets',
  },
  {
    id: 16,
    question: 'What is the Oort Cloud?',
    options: [
      'A storm system on Neptune',
      'A distant spherical shell of icy bodies',
      'The upper layer of Jupiter\'s atmosphere',
      'A type of emission nebula',
    ],
    correct: 1,
    explanation: 'The Oort Cloud is a vast distant region of icy objects thought to surround the solar system at 2,000–100,000 AU.',
    difficulty: 'hard',
    category: 'planets',
  },
  {
    id: 17,
    question: 'How many Earth days does it take Mars to orbit the Sun?',
    options: ['365', '500', '687', '780'],
    correct: 2,
    explanation: 'Mars takes 687 Earth days (about 1.88 Earth years) to complete one full orbit around the Sun.',
    difficulty: 'medium',
    category: 'planets',
  },
  {
    id: 18,
    question: 'What is a neutron star?',
    options: [
      'A very young, newly forming star',
      'The collapsed core of a massive star after a supernova',
      'A dying Sun-like star shedding its outer layers',
      'Another name for a stellar black hole',
    ],
    correct: 1,
    explanation: 'Neutron stars form from the collapsed cores of massive stars after supernova explosions, packing 1–2 solar masses into a sphere ~20 km across.',
    difficulty: 'hard',
    category: 'stars',
  },
  {
    id: 19,
    question: 'Which company first successfully landed and reused an orbital rocket booster?',
    options: ['NASA', 'Blue Origin', 'SpaceX', 'Boeing'],
    correct: 2,
    explanation: 'SpaceX\'s Falcon 9 first successfully landed its first stage booster in December 2015 and reflew it in 2017.',
    difficulty: 'medium',
    category: 'missions',
  },
  {
    id: 20,
    question: 'What does the Chandrasekhar limit define?',
    options: [
      'The maximum speed a rocket can achieve in orbit',
      'The maximum mass a white dwarf star can have',
      'The distance to the nearest galaxy',
      'The estimated age of the universe',
    ],
    correct: 1,
    explanation: 'The Chandrasekhar limit (~1.4 solar masses) is the maximum mass a white dwarf can have before electron degeneracy pressure fails and it collapses.',
    difficulty: 'hard',
    category: 'stars',
  },

  // ── Planets (Q21-Q30) ─────────────────────────────────────────
  {
    id: 21,
    question: 'What is the diameter of Earth in kilometers?',
    options: ['6,371 km', '12,742 km', '8,000 km', '15,000 km'],
    correct: 1,
    explanation: "Earth's diameter is 12,742 km, making it the largest of the four rocky (terrestrial) planets.",
    difficulty: 'medium',
    category: 'planets',
  },
  {
    id: 22,
    question: 'Which planet has the longest day in the solar system?',
    options: ['Mercury', 'Mars', 'Venus', 'Jupiter'],
    correct: 2,
    explanation: 'Venus takes 243 Earth days to rotate once on its axis — longer than any other planet and longer than its own year.',
    difficulty: 'hard',
    category: 'planets',
  },
  {
    id: 23,
    question: "What are Saturn's rings primarily made of?",
    options: ['Volcanic debris', 'Ice and rock fragments', 'Dust from comets', 'Frozen gas'],
    correct: 1,
    explanation: "Saturn's rings consist of countless ice and rock fragments ranging from tiny grains to house-sized chunks.",
    difficulty: 'medium',
    category: 'planets',
  },
  {
    id: 24,
    question: 'Approximately how many Earth masses is Jupiter?',
    options: ['100', '200', '318', '500'],
    correct: 2,
    explanation: 'Jupiter is 318 times the mass of Earth and so voluminous it could contain roughly 1,300 Earths.',
    difficulty: 'hard',
    category: 'planets',
  },
  {
    id: 25,
    question: 'What is the average surface temperature of Mars?',
    options: ['-60°C', '0°C', '-120°C', '20°C'],
    correct: 0,
    explanation: 'Mars averages about -60°C, though temperatures swing from -125°C at the poles to around 20°C near the equator on a summer day.',
    difficulty: 'medium',
    category: 'planets',
  },
  {
    id: 26,
    question: 'Which planet is classified as an "Ice Giant"?',
    options: ['Saturn', 'Jupiter', 'Neptune', 'Pluto'],
    correct: 2,
    explanation: 'Neptune (and Uranus) are classified as ice giants because their interiors are dominated by water, ammonia, and methane ices.',
    difficulty: 'easy',
    category: 'planets',
  },
  {
    id: 27,
    question: 'What is Olympus Mons?',
    options: [
      'A large crater on the Moon',
      'The largest volcano in the solar system',
      'A mountain range on Earth',
      'A canyon on Mars',
    ],
    correct: 1,
    explanation: 'Olympus Mons on Mars stands about 22 km high — nearly three times the height of Mount Everest — making it the tallest volcano in the solar system.',
    difficulty: 'medium',
    category: 'planets',
  },
  {
    id: 28,
    question: 'How long does it take Neptune to orbit the Sun?',
    options: ['84 Earth years', '165 Earth years', '248 Earth years', '120 Earth years'],
    correct: 1,
    explanation: 'Neptune takes 164.8 Earth years per orbit; it has completed just one full orbit since its discovery in 1846.',
    difficulty: 'hard',
    category: 'planets',
  },
  {
    id: 29,
    question: 'What is Valles Marineris?',
    options: [
      'A subsurface sea on Europa',
      'A giant canyon system on Mars',
      'An active volcano on Io',
      'An impact basin on Mercury',
    ],
    correct: 1,
    explanation: 'Valles Marineris is a 4,000 km-long, 7 km-deep canyon system on Mars — roughly the width of the continental United States.',
    difficulty: 'medium',
    category: 'planets',
  },
  {
    id: 30,
    question: 'Which planet has the strongest winds in the solar system?',
    options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    correct: 3,
    explanation: 'Neptune holds the record for the strongest winds in the solar system, reaching up to 2,100 km/h.',
    difficulty: 'hard',
    category: 'planets',
  },

  // ── Stars (Q31-Q38) ───────────────────────────────────────────
  {
    id: 31,
    question: 'What type of star is our Sun?',
    options: ['Red giant', 'White dwarf', 'Yellow dwarf', 'Blue supergiant'],
    correct: 2,
    explanation: 'The Sun is a G-type main-sequence star (yellow dwarf), roughly halfway through its estimated 10-billion-year lifespan.',
    difficulty: 'easy',
    category: 'stars',
  },
  {
    id: 32,
    question: 'What is a supernova?',
    options: [
      'A new star being born from a nebula',
      'A massive stellar explosion',
      'Two stars merging together',
      'A star collapsing into a black hole silently',
    ],
    correct: 1,
    explanation: 'A supernova is an extraordinarily powerful explosion marking the violent death of a massive star, briefly outshining entire galaxies.',
    difficulty: 'easy',
    category: 'stars',
  },
  {
    id: 33,
    question: 'How old is our Sun?',
    options: ['1 billion years', '4.6 billion years', '10 billion years', '500 million years'],
    correct: 1,
    explanation: 'The Sun formed approximately 4.6 billion years ago from the gravitational collapse of a giant molecular cloud.',
    difficulty: 'easy',
    category: 'stars',
  },
  {
    id: 34,
    question: 'What is the Hertzsprung-Russell (H-R) diagram used for?',
    options: [
      'Mapping the positions of galaxies',
      'Classifying stars by temperature and luminosity',
      'Tracking asteroid orbits',
      'Measuring the mass of black holes',
    ],
    correct: 1,
    explanation: 'The H-R diagram plots stars by surface temperature against luminosity, revealing stellar life cycles and main-sequence classifications.',
    difficulty: 'hard',
    category: 'stars',
  },
  {
    id: 35,
    question: 'What color are the hottest stars?',
    options: ['Red', 'Yellow', 'White', 'Blue'],
    correct: 3,
    explanation: 'Stars hotter than ~30,000 K appear blue; cooler stars shift toward yellow, orange, and red — following the same principle as a heated metal rod.',
    difficulty: 'medium',
    category: 'stars',
  },
  {
    id: 36,
    question: 'What is a pulsar?',
    options: [
      'A type of stellar black hole',
      'A rapidly rotating neutron star emitting radio beams',
      'A dying red giant shedding layers',
      'A close binary star system',
    ],
    correct: 1,
    explanation: 'Pulsars are highly magnetized, rapidly spinning neutron stars whose beams of electromagnetic radiation sweep past Earth like a lighthouse.',
    difficulty: 'hard',
    category: 'stars',
  },
  {
    id: 37,
    question: 'Approximately how many stars are in the Milky Way?',
    options: ['1 million', '1 billion', '100–400 billion', '1 trillion'],
    correct: 2,
    explanation: 'Current estimates put the Milky Way at 100 to 400 billion stars, plus a supermassive black hole (Sgr A*) at its center.',
    difficulty: 'medium',
    category: 'stars',
  },
  {
    id: 38,
    question: 'What will our Sun ultimately become at the end of its life?',
    options: ['A neutron star', 'A black hole', 'A white dwarf', 'A supernova remnant'],
    correct: 2,
    explanation: 'The Sun will expand into a red giant in ~5 billion years, shed its outer layers as a planetary nebula, and leave behind a slowly cooling white dwarf.',
    difficulty: 'medium',
    category: 'stars',
  },

  // ── History (Q39-Q45) ─────────────────────────────────────────
  {
    id: 39,
    question: 'Who was the first American to orbit Earth?',
    options: ['Alan Shepard', 'John Glenn', 'Neil Armstrong', 'Buzz Aldrin'],
    correct: 1,
    explanation: 'John Glenn orbited Earth three times aboard Friendship 7 on February 20, 1962, becoming the first American to orbit the planet.',
    difficulty: 'medium',
    category: 'history',
  },
  {
    id: 40,
    question: 'In what year was the Hubble Space Telescope launched?',
    options: ['1985', '1988', '1990', '1993'],
    correct: 2,
    explanation: 'Hubble launched aboard Space Shuttle Discovery on April 24, 1990, and has since made over 1.5 million scientific observations.',
    difficulty: 'medium',
    category: 'history',
  },
  {
    id: 41,
    question: 'What is Apollo 13 famous for?',
    options: [
      'The first crewed Moon landing',
      'A successful lunar rover deployment',
      'An oxygen tank explosion and the crew\'s safe return to Earth',
      'The first American spacewalk',
    ],
    correct: 2,
    explanation: "Apollo 13's oxygen tank exploded en route to the Moon in April 1970; the crew used the lunar module as a lifeboat and safely returned to Earth.",
    difficulty: 'medium',
    category: 'history',
  },
  {
    id: 42,
    question: 'Who was the first woman to travel to space?',
    options: ['Sally Ride', 'Valentina Tereshkova', 'Mae Jemison', 'Christa McAuliffe'],
    correct: 1,
    explanation: 'Soviet cosmonaut Valentina Tereshkova became the first woman in space on June 16, 1963, orbiting Earth 48 times aboard Vostok 6.',
    difficulty: 'easy',
    category: 'history',
  },
  {
    id: 43,
    question: 'In what year did the Space Shuttle Challenger disaster occur?',
    options: ['1983', '1984', '1986', '1988'],
    correct: 2,
    explanation: 'Space Shuttle Challenger broke apart 73 seconds after launch on January 28, 1986, due to an O-ring failure, killing all seven crew members.',
    difficulty: 'medium',
    category: 'history',
  },
  {
    id: 44,
    question: 'Which country was first to land a spacecraft near the lunar south pole?',
    options: ['USA', 'China', 'Russia', 'India'],
    correct: 3,
    explanation: "India's Chandrayaan-3 successfully landed near the lunar south pole on August 23, 2023, making India the fourth country to achieve a soft Moon landing.",
    difficulty: 'medium',
    category: 'history',
  },
  {
    id: 45,
    question: 'What was the first space station to orbit Earth?',
    options: ['Mir', 'ISS', 'Skylab', 'Salyut 1'],
    correct: 3,
    explanation: "The Soviet Union's Salyut 1, launched on April 19, 1971, was the world's first space station, orbiting Earth for 175 days.",
    difficulty: 'hard',
    category: 'history',
  },

  // ── Missions (Q46-Q50) ────────────────────────────────────────
  {
    id: 46,
    question: 'What type of light does the James Webb Space Telescope primarily observe?',
    options: ['Visible light', 'Infrared light', 'X-rays', 'Radio waves'],
    correct: 1,
    explanation: 'JWST is optimized for infrared observation, allowing it to peer through dust clouds and detect light from the earliest galaxies in the universe.',
    difficulty: 'medium',
    category: 'missions',
  },
  {
    id: 47,
    question: 'Where is Voyager 1 as of 2024?',
    options: [
      'Just past the Moon',
      'In the asteroid belt',
      'Just beyond Pluto',
      'In interstellar space',
    ],
    correct: 3,
    explanation: 'Voyager 1, launched in 1977, crossed into interstellar space in 2012 and is now over 24 billion km from Earth — the farthest human-made object ever.',
    difficulty: 'medium',
    category: 'missions',
  },
  {
    id: 48,
    question: "What is the name of NASA's Mars helicopter?",
    options: ['Curiosity', 'Ingenuity', 'Perseverance', 'Pioneer'],
    correct: 1,
    explanation: 'Ingenuity, deployed by the Perseverance rover, made the first powered, controlled flight on another planet on April 19, 2021.',
    difficulty: 'easy',
    category: 'missions',
  },
  {
    id: 49,
    question: 'What is the primary goal of NASA\'s Artemis program?',
    options: [
      'Send the first crewed mission to Mars',
      'Return humans to the Moon',
      'Construct a new Earth-orbit space station',
      'Send a probe to explore Jupiter',
    ],
    correct: 1,
    explanation: "NASA's Artemis program aims to return humans to the Moon — including the first woman and first person of color — as a stepping stone to Mars.",
    difficulty: 'easy',
    category: 'missions',
  },
  {
    id: 50,
    question: 'Which mission first landed on an asteroid and returned samples to Earth?',
    options: ['Rosetta', 'Dawn', 'Hayabusa', 'New Horizons'],
    correct: 2,
    explanation: "JAXA's Hayabusa spacecraft landed on asteroid Itokawa in 2005 and successfully returned samples to Earth in June 2010.",
    difficulty: 'hard',
    category: 'missions',
  },
];
